name: trail_tracker
description: "trail_tracker_app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^0.13.6
  sms_autofill: ^2.0.0
  geolocator: any
  google_maps_flutter: ^2.2.0
  google_place: ^0.4.6
  cloud_firestore: ^4.7.0
  intl: ^0.18.1
  signature: ^4.0.0
  syncfusion_flutter_pdf: ^20.4.48
  path_provider: ^2.0.11
  get_storage: ^2.1.1
  file_picker: ^8.3.1
  pdf: ^3.6.0
  workmanager: ^0.9.0+3
  mappls_gl: ^1.2.0
  webview_flutter: ^4.8.0
  webview_flutter_web: ^0.2.3+4
  js: ^0.6.7
  supabase_flutter: ^1.10.8
  image_picker: ^1.0.5
  path: ^1.8.3
  csv: ^5.0.2
  universal_html: ^2.2.2
  flutter_map: any
  flutter_map_location_marker: any
  device_info_plus: ^10.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
dependency_overrides:
  flutter_compass: ^0.8.1
  sign_in_with_apple: ^7.0.1
